name: metereye_ai
description: Suivi intelligent de compteur CashPower
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  google_fonts: ^6.1.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  flutter_blue_plus: ^1.35.3
  permission_handler: ^11.3.1
  wifi_scan: ^0.4.1
  mobile_scanner: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
